name: rpos_sytem
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
    # Firebase
  font_awesome_flutter: ^8.2.0
  firebase_auth: ^0.8.2
  firebase_database: ^2.0.2
  firebase_storage:
  #image
  image_cropper: ^1.0.0
  image_picker: ^0.5.0+9
  #Google Map
  
  #Video Player
  video_player:
  #Barcode
  barcode_flutter: ^1.0.0
  qrcode_reader: ^0.4.4
  #Gift Dialog
  flutter_spinkit: ^3.1.0
  #Animated Background
  
  #Progress Indicator
  progress_indicators: ^0.1.2   
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #front-end
  # photo:
  cupertino_icons: ^0.1.2
  intro_slider: ^1.1.8
  carousel_slider: ^1.1.0
  flutter_multi_carousel: ^1.0.0
  flutter_staggered_grid_view: ^0.2.7
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/1.jpg
    - assets/image/2.jpg
    - assets/image/3.jpg
    - assets/image/4.jpg
    - assets/image/5.jpg
    - assets/image/6.jpg
    - assets/image/Home.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Light.ttf
    - family: DODGE
      fonts:
        - asset: fonts/New folder/DODGE.ttf
    - family: Hemi Head regarding
      fonts:
        - asset: fonts/New Folder/hemi head bd it.ttf
    - family: Ethoncentric Rg
      fonts:
        - asset: fonts/New Folder/ethnocentric rg.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
